import nikeLab1 from '.././Assent/nikLab1.jpg';
import nikeLab2 from '.././Assent/nikLab2.jpg';
import nikeLab3 from '.././Assent/nikLab3.jpg';
import nikeLab4 from '.././Assent/nikLab4.jpg';
import nikeLab5 from '.././Assent/nikLab5.jpg';
import nikeLab6 from '.././Assent/nikLab6.jpg';
// neseliC
import neseliC1 from '.././Assent/neseliC1.jpg'
import neseliC2 from '.././Assent/neseliC2.jpg'
import neseliC3 from '.././Assent/neseliC3.jpg'
import neseliC4 from '.././Assent/neseliC4.jpg'
import neseliC5 from '.././Assent/neseliC5.jpg'
import neseliC6 from '.././Assent/neseliC6.jpg'
import neseliC7 from '../Assent/neseliC7.jpg'
// hohe
import Hohe1 from '.././Assent/Hohe1.jpg'
import Hohe2 from '.././Assent/Hohe2.jpg'
import Hohe3 from '.././Assent/Hohe3.jpg'
import Hohe4 from '.././Assent/Hohe4.jpg'
// mc
import mc1 from '.././Assent/mc1.png';
import mc2 from '.././Assent/mc2.jpg';
import mc3 from '.././Assent/mc3.jpg';
import mc4 from '.././Assent/mc4.jpg';
import mc5 from '.././Assent/mc5.jpg';
import mc6 from '.././Assent/mc6.jpg';
// baina
import baina1 from '.././Assent/baina1.png'
import baina2 from '.././Assent/baina2.png'
import baina3 from '.././Assent/baina3.jpg'
import baina4 from '.././Assent/baina4.jpg'
import baina5 from '.././Assent/baina5.jpg'
// rick
import rick1 from '.././Assent/rick1.jpg';
import rick2 from '.././Assent/rick2.jpg';
import rick3 from '.././Assent/rick3.jpg';
import rick4 from '.././Assent/rick4.jpg';
import rick5 from '.././Assent/rick5.jpg';
import rick6 from '.././Assent/rick6.jpg';
import rick7 from '.././Assent/rick7.jpg';
import rick8 from '.././Assent/rick8.jpg';
import rick9 from '.././Assent/rick9.jpg';
import rick10 from '.././Assent/rick10.jpg';
import rick11 from '.././Assent/rick11.jpg';

const Products = [
    // naskilar 
    //nikeLab start
    {
        id: 1,
        name: 'Nike Lab',
        image: nikeLab1,
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 96,
    },

    {
        id: 2,
        name: 'Nike Lab',
        image: nikeLab2,
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 42,
    },

    {
        id: 3,
        name: 'Nike Lab',
        image: nikeLab3,
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 81,
    },

    {
        id: 4,
        name: 'Nike Lab',
        image: nikeLab4,
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 13,
    },

    {
        id: 5,
        name: 'Nike Lab',
        image: nikeLab5,
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 75,
    },

    {
        id: 6,
        name: 'Nike Lab',
        image: nikeLab6,
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 64,
    },

    {
        id: 7,
        name: 'Nike Lab',
        image: nikeLab3,
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023', 
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 46,
    },
    // nikeLab end
    //neseliCoraplar start
    {
        id: 8,
        name: 'Neseli Coraplar',
        image: neseliC1,
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 96,
    },

    {
        id: 9,
        name: 'Neseli Coraplar',
        image: neseliC2,
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 76,
    },

    {
        id: 10,
        name: 'Neseli Coraplar',
        image: neseliC3,
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 99,
    },

    {
        id: 11,
        name: 'Neseli Coraplar',
        image: neseliC4,
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 96,
    },

    {
        id: 12,
        name: 'Neseli Coraplar',
        image: neseliC5,
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 106,
    },

    {
        id: 13,
        name: 'Neseli Coraplar',
        image: neseliC6,
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 96,
    },

    {
        id: 14,
        name: 'Neseli Coraplar',
        image: neseliC7,
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 36,
    },

    {
        id: 15,
        name: 'Neseli Coraplar',
        image: neseliC3,
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 66,
    },
        //neseliCoraplar end
        //Hohe start
        {
            id: 16,
            name: 'Hohe',
            image: Hohe1,
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
            like: 89,
        },

        {
            id: 17,
            name: 'Hohe',
            image: Hohe2,
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
            like: 22,
        },

        {
            id: 18,
            name: 'Hohe',
            image: Hohe3,
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
            like: 55,
        },

        {
            id: 19,
            name: 'Hohe',
            image: Hohe4,
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
            like: 43,
        },

        {
            id: 20,
            name: 'Hohe',
            image: Hohe2,
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
            like: 76,
        },
        //hohe end 
        //MC start
    {
        id: 21,
        name: 'MC',
        image: mc1,
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 98,
    },

    {
        id: 22,
        name: 'MC',
        image: mc2,
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 79,
    },

    {
        id: 23,
        name: 'MC',
        image: mc3,
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 16,
    },

    {
        id: 24,
        name: 'MC',
        image: mc4,
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 91,
    },

    {
        id: 25,
        name: 'MC',
        image: mc5,
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 73,
    },

    {
        id: 26,
        name: 'MC',
        image: mc6,
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 62,
    },

    {
        id: 27,
        name: 'MC',
        image: mc3,
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 47,
    },

    {
        id: 28,
        name: 'MC',
        image: mc4,
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 34,
    },

    //MC end
    //baina start

    {
        id: 29,
        name: 'Baina.Socks',
        image: baina1,
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 90,
    },
    {
        id: 30,
        name: 'Baina.Socks',
        image: baina2,
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 103,
    },
    {
        id: 31,
        name: 'Baina.Socks',
        image: baina3,
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023', 
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 74,
    },
    {
        id: 32,
        name: 'Baina.Socks',
        image: baina4,
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 82,
    },
    {
        id: 33,
        name: 'Baina.Socks',
        image: baina5,
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal', 
        like: 96,
    },
    //baina end
    //rick and morty
    {
        id: 34,
        name: 'Rick And Morty',
        image: rick1,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 10,
    },
    {
        id: 35,
        name: 'Rick And Morty',
        image: rick2,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 35,
    },
    {
        id: 36,
        name: 'Rick And Morty',
        image: rick3,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 79,
    },
    {
        id: 37,
        name: 'Rick And Morty',
        image: rick4,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 27,
    },
    {
        id: 38,
        name: 'Rick And Morty',
        image: rick5,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 33,
    },
    {
        id: 39,
        name: 'Rick And Morty',
        image: rick6,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 34,
    },
    {
        id: 40,
        name: 'Rick And Morty',
        image: rick7,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 16,
    },
    {
        id: 41,
        name: 'Rick And Morty',
        image: rick8,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 57,
    },
    //Rick And Morty END
    //Penguin start
    {
        id: 42,
        name: 'Penguin Mill',
        image: rick9,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 78,
    },
    {
        id: 43,
        name: 'Penguin Mill',
        image: rick10,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 95,
    },
    {
        id: 44,
        name: 'Penguin Mill',
        image: rick11,
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
        like: 67,
    },

    //Naski end 

    
]

export default Products