const Products = [
    // naskilar 
    //nikeLab start
    {
        id: 1,
        name: 'Nike Lab',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 2,
        name: 'Nike Lab',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 3,
        name: 'Nike Lab',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 4,
        name: 'Nike Lab',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 5,
        name: 'Nike Lab',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 6,
        name: 'Nike Lab',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 7,
        name: 'Nike Lab',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.04.2023', 
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    // nikeLab end
    //neseliCoraplar start
    {
        id: 8,
        name: 'Neseli Coraplar',
        image: 'src//',
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 9,
        name: 'Neseli Coraplar',
        image: 'src//',
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 10,
        name: 'Neseli Coraplar',
        image: 'src//',
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 11,
        name: 'Neseli Coraplar',
        image: 'src//',
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 12,
        name: 'Neseli Coraplar',
        image: 'src//',
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 13,
        name: 'Neseli Coraplar',
        image: 'src//',
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 14,
        name: 'Neseli Coraplar',
        image: 'src//',
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 15,
        name: 'Neseli Coraplar',
        image: 'src//',
        size: '37 - 44',
        price: '18.000',
        date: '23.03.2023',
        info: '80% PAXTA, 18% POLYAMIDE, 5% ELASTANE',
        produced: 'Turkiya',
        skidka: '15.000',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
        //neseliCoraplar end
        //Hohe start
        {
            id: 16,
            name: 'Hohe',
            image: 'src//',
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
        },

        {
            id: 17,
            name: 'Hohe',
            image: 'src//',
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
        },

        {
            id: 18,
            name: 'Hohe',
            image: 'src//',
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
        },

        {
            id: 19,
            name: 'Hohe',
            image: 'src//',
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
        },

        {
            id: 20,
            name: 'Hohe',
            image: 'src//',
            size: '37 - 44',
            price: '20.000',
            date: '23.02.2023',
            info: '90% PAXTA, 10% POLYAMIDE',
            produced: 'Xitoy',
            skidka: 'Tez kunda',
            humans: 'Male, Female',
            katigoriya: 'Naskilar',
            quality: 'Orginal',
        },
        //hohe end 
        //MC start
    {
        id: 21,
        name: 'MC',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 22,
        name: 'MC',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 23,
        name: 'MC',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 24,
        name: 'MC',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 25,
        name: 'MC',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 26,
        name: 'MC',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 27,
        name: 'MC',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    {
        id: 28,
        name: 'MC',
        image: 'src//',
        size: '34 - 48',
        price: '20.000',
        date: '23.01.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Turkiya',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    //MC end
    //baina start

    {
        id: 29,
        name: 'Baina.Socks',
        image: 'src//',
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 30,
        name: 'Baina.Socks',
        image: 'src//',
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 31,
        name: 'Baina.Socks',
        image: 'src//',
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023', 
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 32,
        name: 'Baina.Socks',
        image: 'src//',
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 33,
        name: 'Baina.Socks',
        image: 'src//',
        size: '25 - 28',
        price: '20.000',
        date: '20.03.2023',
        info: '80% PAXTA, 15% NYLON, 5% SPANDEX',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal', 
    },
    //baina end
    //rick and morty
    {
        id: 34,
        name: 'Rick And Morty',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 35,
        name: 'Rick And Morty',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 36,
        name: 'Rick And Morty',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 37,
        name: 'Rick And Morty',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 38,
        name: 'Rick And Morty',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 39,
        name: 'Rick And Morty',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 40,
        name: 'Rick And Morty',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 41,
        name: 'Rick And Morty',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    //Rick And Morty END
    //Penguin start
    {
        id: 42,
        name: 'Penguin Mill',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 43,
        name: 'Penguin Mill',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },
    {
        id: 44,
        name: 'Penguin Mill',
        image: 'src//',
        size: '40 - 45',
        price: '20.000',
        date: '27.04.2023',
        info: '90% PAXTA, 15% POLIAMID, 2% LAYKRA',
        produced: 'Xitoy',
        skidka: 'Tez Kunda',
        humans: 'Male, Female',
        katigoriya: 'Naskilar',
        quality: 'Orginal',
    },

    //Naski end 

    
]

export default Products